// @ts-nocheck -- skip type checking
import * as docs_9 from "../src/contents/docs/installation/vite.mdx?collection=docs&hash=1758990367659"
import * as docs_8 from "../src/contents/docs/installation/next.mdx?collection=docs&hash=1758990367659"
import * as docs_7 from "../src/contents/docs/get-started/introduction.mdx?collection=docs&hash=1758990367659"
import * as docs_6 from "../src/contents/docs/get-started/installation.mdx?collection=docs&hash=1758990367659"
import * as docs_5 from "../src/contents/docs/get-started/cli.mdx?collection=docs&hash=1758990367659"
import * as docs_4 from "../src/contents/docs/components/textarea.mdx?collection=docs&hash=1758990367659"
import * as docs_3 from "../src/contents/docs/components/separator.mdx?collection=docs&hash=1758990367659"
import * as docs_2 from "../src/contents/docs/components/label.mdx?collection=docs&hash=1758990367659"
import * as docs_1 from "../src/contents/docs/components/input.mdx?collection=docs&hash=1758990367659"
import * as docs_0 from "../src/contents/docs/components/button.mdx?collection=docs&hash=1758990367659"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"components/button.mdx","fullPath":"src/contents/docs/components/button.mdx"}, data: docs_0 }, { info: {"path":"components/input.mdx","fullPath":"src/contents/docs/components/input.mdx"}, data: docs_1 }, { info: {"path":"components/label.mdx","fullPath":"src/contents/docs/components/label.mdx"}, data: docs_2 }, { info: {"path":"components/separator.mdx","fullPath":"src/contents/docs/components/separator.mdx"}, data: docs_3 }, { info: {"path":"components/textarea.mdx","fullPath":"src/contents/docs/components/textarea.mdx"}, data: docs_4 }, { info: {"path":"get-started/cli.mdx","fullPath":"src/contents/docs/get-started/cli.mdx"}, data: docs_5 }, { info: {"path":"get-started/installation.mdx","fullPath":"src/contents/docs/get-started/installation.mdx"}, data: docs_6 }, { info: {"path":"get-started/introduction.mdx","fullPath":"src/contents/docs/get-started/introduction.mdx"}, data: docs_7 }, { info: {"path":"installation/next.mdx","fullPath":"src/contents/docs/installation/next.mdx"}, data: docs_8 }, { info: {"path":"installation/vite.mdx","fullPath":"src/contents/docs/installation/vite.mdx"}, data: docs_9 }], [{"info":{"path":"meta.json","fullPath":"src/contents/docs/meta.json"},"data":{"pages":["get-started","installation","components"]}}, {"info":{"path":"get-started/meta.json","fullPath":"src/contents/docs/get-started/meta.json"},"data":{"pages":["introduction","installation","cli"]}}, {"info":{"path":"installation/meta.json","fullPath":"src/contents/docs/installation/meta.json"},"data":{"pages":["next","vite"]}}])