import type { Metadata } from "next";
import { RootProvider as FumaProvider } from "fumadocs-ui/provider";
import "./globals.css";
import ThemeProvider from "@/components/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <ThemeProvider
          enableSystem={true}
          disableTransitionOnChange={true}
          defaultTheme="system"
          attribute="class"
        >
          <FumaProvider theme={{ enabled: false }}>{children}</FumaProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
