import type { Metadata } from "next";
import fonts from "@/lib/fonts";
import ThemeProvider from "@/components/ThemeProvider";
import RouterProvider from "@/components/RouterProvider";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Chormis UI | Accessible components",
  description: "Generated by create next app",
};

export default function Layout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" suppressHydrationWarning={true} className={fonts}>
      <body className="bg-background text-foreground h-full min-h-svh w-full font-sans text-base font-normal antialiased">
        <RouterProvider>
          <ThemeProvider
            enableSystem={true}
            defaultTheme="system"
            attribute={["class", "data-theme"]}
            disableTransitionOnChange={true}
          >
            {children}
          </ThemeProvider>
        </RouterProvider>
      </body>
    </html>
  );
}
