name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
<<<<<<< HEAD

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

=======
>>>>>>> a1c2738 (ci: :construction_worker: add commitlint workflow (github ci))
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
<<<<<<< HEAD
          cache: 'pnpm'

      - name: Install commitlint
        run: pnpm add -D -w @commitlint/cli @commitlint/config-conventional

=======
          cache: npm
      - name: Install commitlint
        run: npm install -D @commitlint/cli @commitlint/config-conventional
>>>>>>> a1c2738 (ci: :construction_worker: add commitlint workflow (github ci))
      - name: Print versions
        run: |
          git --version
          node --version
<<<<<<< HEAD
          pnpm --version
=======
          npm --version
>>>>>>> a1c2738 (ci: :construction_worker: add commitlint workflow (github ci))
          npx commitlint --version

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
