# .github/workflows/release.yml
name: Version, Tag and Publish

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup pnpm
      - uses: pnpm/action-setup@v4

      # Setup Node.js + registry
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      # Install dependencies
      - run: pnpm install --frozen-lockfile

      # Version, tag & publish
      - name: Version and Publish
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          publish: pnpm -w changeset publish
          commit: "chore: version packages"
          title: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
